lemon: fix C1128
 * add /bigobj flag
 this was necessary after switching to VS Compilter Tools 2019
 for some reason this resulted in Fatal Error C1128
 * also disabled all solver related flags.
 * bump build for vigra, rebuild after changes to lemon